### ISSUE TITLE
bookmark widget is included in out of the box developer edition of wab

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-webappbuilder-widgets-themes#1]
i see the 'bookmark' widget is included with version 1.0 of the developer edition of the web application builder so it doesn't make much sense that its included in this repo too.

**Comment by jgravois** [comment]
same goes for both the included 'custom' themes...

**Comment by tomwayson** [comment]
I agree w/ @jgravois that it doesn't make much sense for this repo to include widgets and themes that are included out of the box

You know what _would_ be useful is to include the old "demo" theme that is no longer included in the release. I've opened #2 to see if there's any support for that idea.

**Comment by jgravois** [comment]
if the purpose of inclusion is to allow for community contributions to some of the out of the box source (ie: bug fixes or additions), that would be pretty cool!  

that being said, we'd need more information in the README to explain what we have in mind because at the moment its not very clear.
